language: node_js
node_js: 10
install: npm ci
script: npm run build
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
